[[plugins]]
repo  = 'jceb/vim-hier'
on_ft = ['ruby', 'php']

[[plugins]]
repo  = 'osyo-manga/shabadou.vim'
on_ft = ['ruby', 'php']

[[plugins]]
repo  = 'dannyob/quickfixstatus'
on_ft = ['ruby', 'php']

[[plugins]]
repo    = 'osyo-manga/vim-watchdogs'
depends = [
  'vim-hier',
  'quickfixstatus',
  'shabadou.vim',
  'vim-quickrun',
]
on_ft    = ['ruby', 'php']
on_event = ['FocusLost', 'CursorHold']
hook_add = '''
  let g:quickrun_config = get(g:, 'quickrun_config', {})
  let g:quickrun_config['watchdogs_checker/_'] = {'outputter/quickfix/open_cmd': ''}
  let g:quickrun_config['watchdogs_checker/jshint'] = {'cmdopt': '--config `/.jshintrc'}
'''
hook_post_source = '''
  call watchdogs#setup(g:quickrun_config)
'''
